### ISSUE TITLE
create controllers for the views

### ISSUE THREAD

**Issue by walidabualafia** [walidabualafia/crowdy#1]
When a user sends a request, the request is routed to a *controller* which defines the response that will be served to the user. For every *view* component, we need to create a *controller*. Please view documentation on MVC if you are unclear about how the components work.

- Controllers should be made and stored in `server/app/controllers`
- Views are stored in `server/app/views`

**Comment by walidabualafia** [comment]
I just pushed code for a sample controller. Based on the api payload, controllers serve the correct output. The latest commit serves generic about data for `localhost:3000/about`.

**Comment by abbyfaulkiner** [comment]
P0
