### ISSUE TITLE
Fix controllers so that they send back JSON objects

### ISSUE THREAD

**Issue by ledd-23** [walidabualafia/crowdy#13]

**Comment by abbyfaulkiner** [comment]
P0

**Comment by walidabualafia** [comment]
This is not a bug. Rails natively serves back html files, it's an `index.html`. I will work on file conversion now, however, you can just manually edit the extension. Everything is formatted in .json.

**Comment by walidabualafia** [comment]
This is for me to keep track. Please ignore this comment.
https://dev.to/caicindy87/rendering-json-in-a-rails-api-25fd
