### ISSUE TITLE
expose the api as a REST API endpoint

### ISSUE THREAD

**Issue by walidabualafia** [walidabualafia/crowdy#17]
Using `heroku`, we need to expose the api to the web. This will allow UI/UX to have a functional API endpoint that is persistently listening. 

This will be useful for our E2E pipeline test for next Tuesday (2/28).

**Comment by walidabualafia** [comment]
P0

**Comment by nabiladem** [comment]
what is the status on this? were we able to ask lang about any ideas/possible solutions?

**Comment by emilyclifton** [comment]
No longer need b/c rtdb is exposed.
